x-api: &api
  image: willdowglas/rinha-backend-2024-q1:latest
  volumes:
    - .:/usr/src/app
  command: bash -c "bundle exec puma -C config/puma.rb"
  depends_on:
      - postgres
  deploy:
    resources:
      limits:
        cpus: '0.3'
        memory: '100MB'

services:
  api1:
    <<: *api
    container_name: api1
  api2:
    <<: *api
    container_name: api2

  postgres:
    image: postgres:16.2
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: '300MB'

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 9999:9999
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '50MB'
